age = int(input("Enter your age: "))
weight = int(input("Enter your weight: "))
height = int(input("Enter your height: "))
aura = int(input("Enter your aura: "))
favorite_language = input("Enter your favortite programing language: ")
print("your age is", age , "your weight is", weight , "your height is", height , "your aura is", aura , "your favorite programing language is", favorite_language)
print(type(age))
print(type(weight))
print(type(height))
print(type(aura))
